apiVersion: anarchy.gpte.redhat.com/v1
kind: AnarchyGovernor
metadata:
  name: example
spec:
  ansibleGalaxyRequirements:
    roles:
    - name: anarchy_example
      src: git+https://github.com/jkupferer/anarchy_example.git
      version: v0.0.1
  runner: default
  pythonRequirements: ''
  subjectEventHandlers:
    create:
      tasks:
      - name: Schedule Configure
        anarchy_schedule_action:
          action: configure

    update:
      tasks:
      - name: Schedule Configure
        anarchy_schedule_action:
          action: configure

    delete:
      tasks:
      - name: Schedule Destroy
        anarchy_schedule_action:
          action: destroy

  actions:
    configure:
      tasks:
      - name: Print message
        debug:
          msg: Running configure for {{ anarchy_subject_name }}

      - name: Run role for configure
        include_role:
          name: anarchy_example
        vars:
          example_app_name: "{{ anarchy_subject_name }}"
          example_namespace: "{{ anarchy_namespace }}"
          example_action: configure

    destroy:
      tasks:
      - name: Print message
        debug:
          msg: Running destroy for {{ anarchy_subject_name }}

      - name: Run role for configure
        include_role:
          name: anarchy_example
        vars:
          example_app_name: "{{ anarchy_subject_name }}"
          example_namespace: "{{ anarchy_namespace }}"
          example_action: destroy

      - name: Complete anarchy subject delete by removing finalizers
        anarchy_subject_delete:
          remove_finalizers: true
